export default {
  BILLING_SUMMARY_FETCHED: 'BILLING_SUMMARY_FETCHED', 
  BILLING_CYCLES_FETCHED: 'BILLING_CYCLES_FETCHED', 
  TAB_SELECTED: 'TAB_SELECTED', 
  TAB_SHOWED: 'TAB_SHOWED',
  TOKEN_VALIDATED: 'TOKEN_VALIDATED', 
  USER_FETCHED: 'USER_FETCHED'
}